language: python
python: 3.5
cache: pip

env:
  - TOXENV=py27-dj18-codecov
  - TOXENV=py27-dj19-codecov
  - TOXENV=py34-dj18-codecov
  - TOXENV=py34-dj19-codecov
  - TOXENV=py35-dj18-codecov
  - TOXENV=py35-dj19-codecov
  - TOXENV=pypy-dj18-codecov
  - TOXENV=pypy-dj19-codecov
  - TOXENV=pypy3-dj18-codecov
  - TOXENV=pypy3-dj19-codecov

matrix:
  allow_failures:
    # PyPy3 on Travis seems to be broken, as of 2016-02.
    #
    # See: https://github.com/travis-ci/travis-ci/issues/4306
    #
    - env: TOXENV=pypy3-dj18-codecov
    - env: TOXENV=pypy3-dj19-codecov

# Avoid overriding the default install step,
# so that automatic pip caching works.
#
# See: https://github.com/travis-ci/travis-ci/issues/3239
#
before_script:
  - pip install tox

script:
  - tox
