language: python
python: 3.5
cache: pip

env:
  - TOXENV=py27-dj18
  - TOXENV=py27-dj19
  - TOXENV=py34-dj18
  - TOXENV=py34-dj19
  - TOXENV=py35-dj18
  - TOXENV=py35-dj19
  - TOXENV=pypy-dj18
  - TOXENV=pypy-dj19
  - TOXENV=pypy3-dj18
  - TOXENV=pypy3-dj19

# Avoid overriding the default install step,
# so that automatic pip caching works.
#
# See: https://github.com/travis-ci/travis-ci/issues/3239
#
before_install:
  - pip install tox

script:
  - tox
